language: python
matrix:
  include:
    - name: "Python 3.7.4 on Windows"
      os: windows
      language: shell
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - name: "Python 3.7.1 on Linux"
      python: 3.7.1
      language: python
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11
      language: shell
  allow_failures:
    - os: linux
    - os: osx

if: branch IN (master, fix-travis)

before_install:
  - git config --global user.email ${USER_EMAIL}
  - git config --global user.name ${USER_NAME}
  - export TRAVIS_TAG="v$(cat ./amulet_map_editor/version)"
  - if [ $(git tag -l "${TRAVIS_TAG}") ] ; then travis_terminate 1 ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ] ; then choco install python --version 3.7.5; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ] ; then python -m pip install --upgrade pip ; fi
  - export ZIPFILE_NAME="Amulet-${TRAVIS_TAG}-${TRAVIS_OS_NAME}"

install:
  - pip3 install --upgrade pip
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then source ./.travis/osx_setup_python.sh 3.7.1 10.6 ; fi
#  - if [ "$TRAVIS_OS_NAME" = "osx" ] || [ "$TRAVIS_OS_NAME" = "windows" ] ; then pip3 install --user --upgrade setuptools wheel ; else pip3 install --upgrade setuptools wheel ; fi
#  - if [ "$TRAVIS_OS_NAME" = "osx" ] || [ "$TRAVIS_OS_NAME" = "windows" ] ; then pip3 install --user -r requirements.txt ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] || [ "$TRAVIS_OS_NAME" = "windows" ] ; then pip3 install --user --upgrade setuptools wheel ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] || [ "$TRAVIS_OS_NAME" = "windows" ] ; then pip3 install --user -r requirements.txt ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ] ; then pip3 install pypiwin32 ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]
  - if [ "$TRAVIS_OS_NAME" = "linux" ] ; then pip3 install -r requirements_linux.txt ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ] || [ "$TRAVIS_OS_NAME" = "linux" ] ; pip3 install pyinstaller>=3.5 ; fi
  - wget https://raw.githubusercontent.com/gentlegiantJGC/PyMCTranslate/master/minify_json.py
  - if [ "$TRAVIS_OS_NAME" = "windows" ] || [ "$TRAVIS_OS_NAME" = "linux" ] ; then pyinstaller -y Amulet.spec ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then bash ./.travis/osx_build_app.sh AmuletApp $TRAVIS_TAG

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ] ; then 7z a "${ZIPFILE_NAME}.zip" -r ./dist/* ; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ] ; then cd dist/ || cd dist_app/ ; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ] ; then zip -r "${ZIPFILE_NAME}.zip" "Amulet" -x "*/\.DS_Store" ; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ] ; then cp "${ZIPFILE_NAME}.zip" ../ ; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ] ; then cd .. ; fi

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    name: "Amulet $TRAVIS_TAG"
    draft: true
    prerelease: true
    skip_cleanup: true
    file_glob: true
    file: '*.zip'
    tag_name: $TRAVIS_TAG

notifications:
  email: false
