name: Docker Image CI

on:
  workflow_run:
    workflows: [python-build]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build \
          . \
          --file Dockerfile \
          --tag amulet-editor:latest \
          --build-arg AMULET_VERSION=${{ github.event.release.tag_name }}

    - name: Save Docker image to tar archive
      run: |
        docker save amulet-editor:latest -o amulet-editor.tar

    - name: Upload Release Asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ github.event.release.tag_name }} \
          amulet-editor.tar#Amulet-v${{ github.event.release.tag_name }}-docker.tar