name: Build Docker

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build \
          . \
          --file Dockerfile \
          --tag amulet-editor:latest \
          --build-arg AMULET_VERSION=CUSTOM:git+https://github.com/${{ github.repository }}.git@${{ github.event.release.tag_name }}

    - name: Save and compress Docker image
      run: |
        docker save amulet-editor:latest | xz -9e > Amulet-v${{ github.event.release.tag_name }}-docker.tar.gz

    - name: Upload Release Asset
      uses: actions/upload-artifact@v4
      with:
        name: Amulet-v${{ github.event.release.tag_name }}-docker.tar.gz
        path: Amulet-v${{ github.event.release.tag_name }}-docker.tar.gz
