# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ${{ matrix.cfg.os }}
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        cfg:
        - {os: windows-2025, python-version: '3.11', architecture: x64}
        - {os: macos-15-intel, python-version: '3.11', architecture: x64}
        - {os: macos-15, python-version: '3.11', architecture: arm64}
        - {os: ubuntu-24.04, python-version: '3.11', architecture: x64}

    steps:
    - name: Clone
      uses: actions/checkout@v6

    - name: Set up Python ${{ matrix.cfg.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.cfg.python-version }}

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine pyinstaller~=6.18 build

    - name: Linux - Install dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update && sudo apt-get install -y \
          libgtk-3-0 \
          dbus-x11 \
          libnotify4 \
          libsdl2-2.0-0 \
          libsm6 \
          libcurl4 \
          libsecret-1-0 \
          libpcre2-32-0 \
          xdg-utils \
          libopengl0 \
          libgl1 \
          libgl1-mesa-dri \
          libegl1 \
          libegl-mesa0
        pip install https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-24.04/wxpython-4.2.5-cp311-cp311-linux_x86_64.whl

    - name: Setup
      run: |
        export BDISTWHEELFREEZELIBS=true
        python -m build
        python -m pip install dist/amulet_map_editor-*.whl --upgrade

    - name: MacOS - Store Credentials
      if: runner.os == 'macOS'
      run: |
        xcrun notarytool store-credentials \
          "notary-profile" \
          --apple-id "${{ secrets.APPLE_ID }}" \
          --team-id "${{ secrets.APPLE_TEAM_ID }}" \
          --password "${{ secrets.APPLE_PASSWORD }}"

    - name: MacOS - Import Developer ID Certificate
      if: runner.os == 'macOS'
      run: |
        CERTIFICATE_PATH=$RUNNER_TEMP/developer_id.p12
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

        echo -n "${{ secrets.APPLE_P12_BASE64 }}" | base64 --decode -o "$CERTIFICATE_PATH"

        security create-keychain -p "${{ secrets.APPLE_KEYCHAIN_PASSWORD }}" "$KEYCHAIN_PATH"
        security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
        security unlock-keychain -p "${{ secrets.APPLE_KEYCHAIN_PASSWORD }}" "$KEYCHAIN_PATH"

        security import "$CERTIFICATE_PATH" -P "${{ secrets.APPLE_P12_PASSWORD }}" -A -t cert -f pkcs12 -k "$KEYCHAIN_PATH"
        security set-key-partition-list -S apple-tool:,apple: -k "${{ secrets.APPLE_KEYCHAIN_PASSWORD }}" "$KEYCHAIN_PATH"
        security list-keychain -d user -s "$KEYCHAIN_PATH"
        security default-keychain -s "$KEYCHAIN_PATH"

    - name: PyInstaller build
      env:
        APPLE_CODESIGN_IDENTITY: ${{ secrets.APPLE_CODESIGN_IDENTITY }}
      run: |
        python -m PyInstaller -y --distpath ./installer/dist installer/Amulet.spec

    - name: Windows - Install NSIS
      if: runner.os == 'Windows'
      uses: repolevedavaj/install-nsis@v1.1.0
      with:
        nsis-version: '3.11'

    - name: Windows - Sign and Create Installer
      if: runner.os == 'Windows'
      run: |
        curl -L -o azuresigntool.exe https://github.com/vcsjones/AzureSignTool/releases/download/v7.0.1/AzureSignTool-x64.exe
        find ./installer/dist/amulet -type f \( -name "*.exe" -o -name "*.dll" -o -name "*.pyd" \) -exec ./azuresigntool.exe sign -kvu "${{ secrets.KEY_VAULT_URL }}" -kvc "${{ secrets.KEY_VAULT_CERTIFICATE }}" -kvi "${{ secrets.KEY_VAULT_CLIENT_ID }}" -kvs "${{ secrets.KEY_VAULT_SECRET }}" -kvt "${{ secrets.KEY_VAULT_TENANT }}" -tr http://timestamp.digicert.com -v "{}" \;
        makensis -DVERSION=${{ github.event.release.tag_name }} installer/windows.nsi
        ./azuresigntool.exe sign -kvu "${{ secrets.KEY_VAULT_URL }}" -kvc "${{ secrets.KEY_VAULT_CERTIFICATE }}" -kvi "${{ secrets.KEY_VAULT_CLIENT_ID }}" -kvs "${{ secrets.KEY_VAULT_SECRET }}" -kvt "${{ secrets.KEY_VAULT_TENANT }}" -tr http://timestamp.digicert.com -v "./installer/dist/Amulet-${{ github.event.release.tag_name }}-Windows-x64.exe"
        rm -rf installer/dist/amulet

    - name: MacOS - Create DMG
      if: runner.os == 'macOS'
      run: |
        brew install create-dmg
        mkdir -p "installer/dist/dmg"
        ditto "installer/dist/amulet.app" "installer/dist/dmg/amulet.app"
        codesign --verify --deep --strict installer/dist/dmg/amulet.app
        create-dmg \
          --volname "Amulet-${{ github.event.release.tag_name }}" \
          --volicon "installer/logo.icns" \
          --window-pos 200 120 \
          --window-size 600 300 \
          --icon-size 100 \
          --icon "amulet.app" 175 120 \
          --hide-extension "amulet.app" \
          --app-drop-link 425 120 \
          "installer/dist/Amulet-${{ github.event.release.tag_name }}-macOS-${{ matrix.cfg.architecture }}.dmg" \
          "installer/dist/dmg"
        rm -rf installer/dist/amulet.app
        rm -rf installer/dist/amulet
        rm -rf installer/dist/dmg

    - name: MacOS - Notarise DMG
      if: runner.os == 'macOS'
      run: |
        xcrun notarytool submit \
          "installer/dist/Amulet-${{ github.event.release.tag_name }}-macOS-${{ matrix.cfg.architecture }}.dmg" \
          --keychain-profile "notary-profile" \
          --team-id "${{ secrets.APPLE_TEAM_ID }}" \
          --wait
        xcrun stapler staple \
          "installer/dist/Amulet-${{ github.event.release.tag_name }}-macOS-${{ matrix.cfg.architecture }}.dmg"

    - name: Linux - Package
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install ruby
        sudo gem install fpm
        
        # Copy app
        mkdir -p installer/dist/deb/opt
        cp -r installer/dist/amulet installer/dist/deb/opt/amulet_map_editor
        
        # Copy logo
        mkdir -p installer/dist/deb/usr/share/icons/hicolor/512x512/apps
        cp installer/amulet_logo_512.png installer/dist/deb/usr/share/icons/hicolor/512x512/apps/amulet_map_editor.png
        
        # Create desktop file
        mkdir -p installer/dist/deb/usr/share/applications
        cat << EOF > installer/dist/deb/usr/share/applications/amulet_map_editor.desktop
        [Desktop Entry]
        Type=Application
        Name=Amulet ${{ github.event.release.tag_name }}
        Comment=A Minecraft world editor and converter that supports all versions since Java 1.12 and Bedrock 1.7.
        Path=/opt/amulet_map_editor
        Exec=/opt/amulet_map_editor/amulet
        Icon=amulet_map_editor
        EOF
        
        # Set Permissions
        find installer/dist/deb/opt/amulet_map_editor -type f -exec chmod 644 -- {} +
        find installer/dist/deb/opt/amulet_map_editor -type d -exec chmod 755 -- {} +
        find installer/dist/deb/usr/share -type f -exec chmod 644 -- {} +
        chmod +x installer/dist/deb/opt/amulet_map_editor/amulet
        chmod +x installer/dist/deb/opt/amulet_map_editor/amulet_debug
        
        # Build the package
        fpm \
          --chdir installer/dist/deb \
          --input-type dir \
          --output-type deb \
          --name "amulet-map-editor" \
          --version ${{ github.event.release.tag_name }} \
          --description "A Minecraft world editor and converter that supports all versions since Java 1.12 and Bedrock 1.7." \
          --url https://www.amuletmc.com \
          --maintainer "James Clare (gentlegiantJGC) <amuleteditor@gmail.com>" \
          --architecture native \
          --package installer/dist/Amulet-${{ github.event.release.tag_name }}-Linux-x86_64.deb
        
        rm -rf installer/dist/amulet
        rm -rf installer/dist/deb

    - name: Publish to PyPi
      if: runner.os != 'Linux'
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.AMULET_MAP_EDITOR_PYPI_PASSWORD }}
      run: |
        twine upload dist/amulet[_-]map[_-]editor*.tar.gz --skip-existing

    - name: Upload Release Asset
      uses: actions/upload-artifact@v6
      with:
        name: Amulet-${{ github.event.release.tag_name }}-${{ runner.os }}-${{ matrix.cfg.architecture }}
        path: ./installer/dist
